version: '3'

services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ownomad
      - POSTGRES_USER=postgres
      # Please provide your own password.
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  # redis:
  #   image: redis:alpine
  #   restart: always
  #   command: ["sh", "-c", "redis-server --requirepass \"$REDIS_PASSWORD\""]
  #   env_file: .env
  #   volumes:
  #     - ./.data/redis:/data
  #   ports:
  #     - '127.0.0.1:6379:6379'
